# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/js_monitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/js_monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protos/js_monitor.proto\x12\tjsmonitor\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n\x0cJsFileCreate\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x12\n\ncompany_id\x18\x03 \x01(\t\";\n\x11\x41\x64\x64JsFilesRequest\x12&\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x17.jsmonitor.JsFileCreate\">\n\x12\x41\x64\x64JsFilesResponse\x12(\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x19.jsmonitor.JsFileResponse\"5\n\"FetchAndUpdateJsFileContentRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"?\n\x12ListJsFilesRequest\x12\x12\n\ncompany_id\x18\x01 \x01(\t\x12\x15\n\rfetch_content\x18\x02 \x01(\x08\"?\n\x13ListJsFilesResponse\x12(\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x19.jsmonitor.JsFileResponse\"\xe3\x01\n\x0eJsFileResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x14\n\x07\x63ontent\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x08priority\x18\x05 \x01(\x05\x12\x12\n\ncompany_id\x18\x06 \x01(\t\x12\x30\n\x0clast_fetched\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0clast_updated\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\n\n\x08_content2\x94\x02\n\x10JSMonitorService\x12I\n\nAddJsFiles\x12\x1c.jsmonitor.AddJsFilesRequest\x1a\x1d.jsmonitor.AddJsFilesResponse\x12g\n\x1b\x46\x65tchAndUpdateJsFileContent\x12-.jsmonitor.FetchAndUpdateJsFileContentRequest\x1a\x19.jsmonitor.JsFileResponse\x12L\n\x0bListJsFiles\x12\x1d.jsmonitor.ListJsFilesRequest\x1a\x1e.jsmonitor.ListJsFilesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.js_monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSFILECREATE']._serialized_start=71
  _globals['_JSFILECREATE']._serialized_end=136
  _globals['_ADDJSFILESREQUEST']._serialized_start=138
  _globals['_ADDJSFILESREQUEST']._serialized_end=197
  _globals['_ADDJSFILESRESPONSE']._serialized_start=199
  _globals['_ADDJSFILESRESPONSE']._serialized_end=261
  _globals['_FETCHANDUPDATEJSFILECONTENTREQUEST']._serialized_start=263
  _globals['_FETCHANDUPDATEJSFILECONTENTREQUEST']._serialized_end=316
  _globals['_LISTJSFILESREQUEST']._serialized_start=318
  _globals['_LISTJSFILESREQUEST']._serialized_end=381
  _globals['_LISTJSFILESRESPONSE']._serialized_start=383
  _globals['_LISTJSFILESRESPONSE']._serialized_end=446
  _globals['_JSFILERESPONSE']._serialized_start=449
  _globals['_JSFILERESPONSE']._serialized_end=676
  _globals['_JSMONITORSERVICE']._serialized_start=679
  _globals['_JSMONITORSERVICE']._serialized_end=955
# @@protoc_insertion_point(module_scope)
