# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import js_monitor_pb2 as protos_dot_js__monitor__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/js_monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JSMonitorServiceStub(object):
    """Service definition for monitoring JavaScript files.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddJsFiles = channel.unary_unary(
                '/jsmonitor.JSMonitorService/AddJsFiles',
                request_serializer=protos_dot_js__monitor__pb2.AddJsFilesRequest.SerializeToString,
                response_deserializer=protos_dot_js__monitor__pb2.AddJsFilesResponse.FromString,
                _registered_method=True)
        self.FetchAndUpdateJsFileContent = channel.unary_unary(
                '/jsmonitor.JSMonitorService/FetchAndUpdateJsFileContent',
                request_serializer=protos_dot_js__monitor__pb2.FetchAndUpdateJsFileContentRequest.SerializeToString,
                response_deserializer=protos_dot_js__monitor__pb2.JsFileResponse.FromString,
                _registered_method=True)
        self.ListJsFiles = channel.unary_unary(
                '/jsmonitor.JSMonitorService/ListJsFiles',
                request_serializer=protos_dot_js__monitor__pb2.ListJsFilesRequest.SerializeToString,
                response_deserializer=protos_dot_js__monitor__pb2.ListJsFilesResponse.FromString,
                _registered_method=True)


class JSMonitorServiceServicer(object):
    """Service definition for monitoring JavaScript files.
    """

    def AddJsFiles(self, request, context):
        """Adds one or more new JavaScript files to the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAndUpdateJsFileContent(self, request, context):
        """Fetches the content for a specific file and updates the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJsFiles(self, request, context):
        """Lists all JS files, optionally filtered by company ID and with optional content fetching.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JSMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddJsFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.AddJsFiles,
                    request_deserializer=protos_dot_js__monitor__pb2.AddJsFilesRequest.FromString,
                    response_serializer=protos_dot_js__monitor__pb2.AddJsFilesResponse.SerializeToString,
            ),
            'FetchAndUpdateJsFileContent': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAndUpdateJsFileContent,
                    request_deserializer=protos_dot_js__monitor__pb2.FetchAndUpdateJsFileContentRequest.FromString,
                    response_serializer=protos_dot_js__monitor__pb2.JsFileResponse.SerializeToString,
            ),
            'ListJsFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJsFiles,
                    request_deserializer=protos_dot_js__monitor__pb2.ListJsFilesRequest.FromString,
                    response_serializer=protos_dot_js__monitor__pb2.ListJsFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jsmonitor.JSMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jsmonitor.JSMonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JSMonitorService(object):
    """Service definition for monitoring JavaScript files.
    """

    @staticmethod
    def AddJsFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jsmonitor.JSMonitorService/AddJsFiles',
            protos_dot_js__monitor__pb2.AddJsFilesRequest.SerializeToString,
            protos_dot_js__monitor__pb2.AddJsFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchAndUpdateJsFileContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jsmonitor.JSMonitorService/FetchAndUpdateJsFileContent',
            protos_dot_js__monitor__pb2.FetchAndUpdateJsFileContentRequest.SerializeToString,
            protos_dot_js__monitor__pb2.JsFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJsFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jsmonitor.JSMonitorService/ListJsFiles',
            protos_dot_js__monitor__pb2.ListJsFilesRequest.SerializeToString,
            protos_dot_js__monitor__pb2.ListJsFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
